[package]
name = "hex2bytes"
version = "0.1.0"
authors = ["iStrike7 <siddiquishoeb.iitm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex={}
sp-core = '2.0.0'
